<?php

class MageNet_Eav_Model_Resource_Post_Collection extends Mage_Eav_Model_Entity_Collection_Abstract
{
    protected function _construct()
    {
        $this->_init('magenet_eav/post');
    }

    public function addAttributeToSelect($attribute, $joinType = false)
    {
        return parent::addAttributeToSelect($attribute, $joinType); // TODO: Change the autogenerated stub
    }
}
